name: dreamcil
description: A new Flutter application.

publish_to: 'none' # Remove this l
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_screenutil: ^0.4.2
  permission_handler: ^5.0.1+1
  font_awesome_flutter: ^8.8.1
  bubble_tab_indicator: ^0.1.4
  google_fonts: ^1.1.0
  share: ^0.6.4+3
  sqflite:
  get_it:
  localstorage:
  scoped_model: ^1.0.1
  equatable: ^1.1.0
  flutter_bloc: ^3.1.0
  fluttertoast: ^3.1.3
  carousel_pro: ^1.0.0
  google_sign_in: ^4.5.1
  page_transition: ^1.1.5
  firebase_auth_ui: ^1.0.1
  firebase_core: ^0.4.4+3
  firebase_crashlytics: ^0.1.4+1
  firebase_auth: ^0.16.0
  url_launcher: ^5.5.0
  sticky_headers: ^0.1.8+1
  flutter_rating: ^0.0.2
  documents_picker: ^1.0.0
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.15
  firebase_analytics: ^5.0.14
  introduction_screen: ^1.0.9
  flutter_secure_storage: ^3.3.1+1
  data_connection_checker: ^0.3.4
  youtube_player_flutter: ^7.0.0+7
  flutter_staggered_grid_view: ^0.3.2
  flutter_local_notifications: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/banner/
    - assets/image_01.png
    - assets/image_02.png
    - assets/logo.png

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf



